display_name: Soya Music
package_name: soyamusic
maintainer:
  name: sadevelopment
priority: optional
section: x11
installed_size: 20000

dependencies:
  - mpv
  - libmpv1 | libmpv2
  - libappindicator3-1 | libayatana-appindicator3-1

essential: false
icon: assets/icons/icon.png

keywords:
  - Opensource
  - Music
  - Streaming
  - Flutter

generic_name: Music Application

categories:
  - Music