name: Build Windows exe 
on: workflow_dispatch
  
jobs:

  build-windows-exe:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.2'
          
      - name: Clone project
        run: git clone https://github.com/SoulDevs/Soya-Music.git

      - name: Update lang data
        working-directory: ./Soya-Music
        run: dart localization/generator.dart

      - name: Set update check flag to true
        working-directory: ./Soya-Music/lib/utils
        run: echo "const updateCheckFlag = true;" > update_check_flag_file.dart
        
      - name: Build windows exe package
        working-directory: ./Soya-Music
        run: |
          flutter clean
          dart pub global activate flutter_distributor
          flutter_distributor package --platform windows --targets exe
          
      - name: Upload Windows exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: Soya music windows exe
          path: ./Soya-Music/dist/*
